version: '2'
services:
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    environment:
      ADV_HOST: 127.0.0.1           # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                   # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                   # Zookeeper
      - 3030:3030                   # Landoop UI
      - 8082-8084:8082-8084         # REST Proxy, Schema Registry, Kafka Connect Ports
      - 9581-9585:9581-9585         # JMX Ports
      - 9092:9092                   # Kafka Broker

  # We will use elasticsearch as one of our sinks.
  # This configuration allows you start elasticsearch
  elasticsearch:
    image: nshou/elasticsearch-kibana:latest
    ports:
      - 9200:9200                   # Elasticsearch Port
      - 5600:5600                   # Kibana Port

  # We will use postgres as one of our sinks.
  # This configuration allows you start postgres
  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres       # define credential
      POSTGRES_PASSWORD: postgres   # define credential
      POSTGRES_DB: postgres         # define db
    ports:
      - 5432:5432                   # Postgres ports